FROM resin/raspberrypi3-python:2.7

WORKDIR /app

RUN apt-get update && \
    apt-get install libgtk2.0-dev && \
    apt-get install -y --no-install-recommends libboost-python1.62.0 python3-pip libpython3-dev && \
    rm -rf /var/lib/apt/lists/* 

RUN pip install --upgrade setuptools 
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT [ "python", "-u", "./main.py" ]